---
machines:
  hg_web:
    hostname: "hg_web"
    ipv4: "192.168.73.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/howdengroup/"
      owner: www-data
      group: www-data

  hg_db:
    hostname: "hg_db"
    ipv4: "192.168.73.20"
    playbook: "provisioning/ansible/db_server.yml"
